### ISSUE TITLE
Pivot table aggregation methods like `median` should be disabled for non-number columns

### ISSUE THREAD

**Issue by naterush** [mito-ds/monorepo#121]
**Describe the bug**

Add a row to a pivot table, and then a value that is a string column. Set the aggregation method to `mean`, and get an error.

**Expected behavior**

The invalid options for the value aggregation should be disabled (with an error message) on non-number columns (e.g. everything but count, and count unique).

**Comment by aarondr77** [comment]
Another helpful tooltip would be that if you set the aggregation method to `standard deviation`, then for any key that has a count of 1, the standard deviation is undefined and that key is excluded from the pivot table.
