### ISSUE TITLE
No way to sign up for Mito Pro after signed in

### ISSUE THREAD

**Issue by jake-stack** [mito-ds/monorepo#129]
Currently, there is no way to sign up for Mito Pro after you finish the signing process, without using the installer. We should make it easy to sign up for Mito Pro. 

Probably the easiest solution is a simple modal with an input that allows you to signup for Pro; that's it!

**Comment by naterush** [comment]
Another thing that would be nice here is adding some icon so that users know they have a pro account.

**Comment by aarondr77** [comment]
There is now a way for users to signup for Pro in the app + we tell users which version of Mito they are on.
