### ISSUE TITLE
Summary stats to reflect number format for selected column

### ISSUE THREAD

**Issue by plasmonresonator** [mito-ds/monorepo#135]
I just noticed that when I changed the number type of a specific column (say to Accounting style), the values displayed in the summary statistics window are still formatted generically.  Not a huge deal, but would be nice if those numbers were displayed using a similar number format that is assigned to the selected column.

**Comment by naterush** [comment]
@plasmonresonator thanks for the bug report! Updating this certainly makes sense. Here's how we might go about this:
```
count: no formatting changes
mean: formatting matches column
std: formatting matches column
min: formatting matches column
25%: formatting matches column
50%: formatting matches column
75%: formatting matches column
max: formatting matches column
count: nan: no formatting changes
median: formatting matches column
sum: formatting matches column
```

We simply need to use the helper function that displays the column values - passing the dtype - so nothing challenging here!

**Comment by naterush** [comment]
@plasmonresonator the linked PR above addresses this. This will most likely make it into our release next week. Thanks again for the bug report - keep em coming :-)
