### ISSUE TITLE
Add types to remaining functions

### ISSUE THREAD

**Issue by naterush** [mito-ds/monorepo#17]
We still have bugs in our Python code as a result of no types on our functions. This is a bigger issue in the API where there is no type on the step manager (which we need to fix, because circular imports).

**Comment by naterush** [comment]
Ok, I opened #29 PR, which does a lot of this work. There are two major changes I want to do still before calling this done:
1. Add an explicit ColumnHeader and ColumnID type; I think this will _greatly_ improve clarity of the codebase, and make clear what we're working with.
2. Add an explicitly Event type. For the same reason.

**Comment by aarondr77** [comment]
Yeah, I think having a ColumnHeader and ColumnID type would be incredibly helpful. Both in Python and Typescript. Trying to figure out if the string type in an object is the columnHeader or columnID forces me to go back to the comments in the types.tsx file all the time. Enforcing that the type is correct in the type system would be super helpful.

**Comment by naterush** [comment]
@aarondr77 PR #32 does this on the Python side; we can and will add explicit type aliases for ColumnIDs in Typescript as well, before closing this issue.
