### ISSUE TITLE
Sometimes Graphs appear half-sized in the tab

### ISSUE THREAD

**Issue by jake-stack** [mito-ds/monorepo#191]
**Describe the bug**
Sometimes the graphs appear as half the screen size that they should. If you look at the images that this user tweeted you can see it:[tweet]( https://twitter.com/DataKimist/status/1507171055558873091?s=20&t=yjtuDMerp8HY7m82s5Amnw)

**To Reproduce**
Not sure what the steps are, but I have seen this multiple times.

Please include the relevant dataset if the bug you encountered is dataset specific. Make sure to anonymize the data properly.

**Expected behavior**
I would expect the graph to be full sized. 

**Screenshots**
in tweet above.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [e.g. Chrome, Firefox]
 - Mito Version [e.g. 0.3.331] (you can find this with `pip list`)

not sure

**Additional context**

This the second user I have seen have this issue.

**Comment by naterush** [comment]
@jake-stack this is addressed in dev and will be deployed before EOW. 


In the future, can you try and backtrack from the features that the user had -> what version they were likely on? This will make it _much_ easier to figure out if this is something we need to fix or if it's already been fixed, making these bug reports way more valuable. 

Also, feel free to clear out the prompts and just keep the section headers + your reponses, so it's easy to read.
