### ISSUE TITLE
Rename while doing an operation causes an error

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#211]
**To Reproduce**
1. Import a dataframe, duplicate it.
2. Click on CONCAT and notice a new dataframe appears
3. Rename the new dataframe 
4. Add a new file to the concat configuration
5. Notice this error. 

<img width="740" alt="Screen Shot 2022-04-04 at 12 18 42 AM" src="https://user-images.githubusercontent.com/18709905/161473169-e8ab20e4-50fb-48e2-ad9b-db9919f8318a.png">

The same bug exists with other operations as well, like pivot table.

**Comment by naterush** [comment]
@aarondr77 can we just close editing taskpanes on dataframe rename? I think this is the easiest solution.
