### ISSUE TITLE
Column header context menu not opening 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#299]
**Describe the bug**
I was working with a user and when they used their mouse to right click on the column header, the context menu that appeared was the browser context menu. Not Mito's.

- Mitosheet: 0.1.421
- Browser: Chrome 101.0.4951.54
- Windows Desktop with a mouse

**Comment by aarondr77** [comment]
I was able to recreate this on my windows laptop. 
- Mitosheet: 0.1.421
- Chrome version 101.0.4951.54

The chrome browser context menu appears. However, if I look in the console, the message `sending right_clicked_on_column_header` does appear.

**Comment by aarondr77** [comment]
This does work in development mode on `main`. 

It looks like the last GitHub action on main failed to deploy the mitoinstaller & mitosheet, so either:
1) This is some prod / dev issue of which we've seen before due to react builds
2) The context menu actually just didn't get released

I'm guessing 2

**Comment by aarondr77** [comment]
It errored while building the extension with `ValueError: Extensions require a devDependency on @jupyterlab/builder@^3.4.1, you have a dependency on 3.0.8`

**Comment by naterush** [comment]
I don't think that this error should occur with mitosheet and not mitosheet3, because they are effectively the same package. I think that just rerunning the deploy might fix this. I'll check this.

**Comment by naterush** [comment]
It worked! I noticed you reran it, but I think it might have just been a temporary bug. We'll see if this comes up again...
