### ISSUE TITLE
Provide: jupyter labextension install mitosheet

### ISSUE THREAD

**Issue by congineer** [mito-ds/monorepo#315]
PROBLEM: container script automation.
the install documentation for Docker/Vagrant suggests only classic notebook way, i.e. 

`jupyter nbextension install mitosheet`

When trying to install for labbooks I get semver conflicts (see pic attached):

`jupyter labextension install mitosheet`

![jupyter_labextension_install_mitosheet_Screenshot_20220525_181046](https://user-images.githubusercontent.com/11654117/170312433-76e8ce06-422c-46b0-bae0-ba13b971a7da.png)

SOLUTION: a) force install or b) alternative way
a) provide how to force the `mitosheet` labextension install or 
b) a flag for `mitoinstaller` that installs classic and lab extensions, BUT suppresses the final lab server launch on URL.

**Comment by naterush** [comment]
Hey @congineer  - sorry you ran into these issues! A few thoughts:

1. We certainly should provide a flag to suppress the launch of JupyterLab from the installer. This is a no-brainer, and would be very easy to add. 
2. You don't need to run the `jupyter labextension install mitosheet` command for JupyterLab 3.0 or greater. Just the pip install will work by itself.

I'll improve the docs on (2) to make it more clear, but feel free to just leave out this step. If you `pip install mitosheet`, it will work for lab > 3.0 out of the box with no extra work!

**Comment by congineer** [comment]
Thanks @[naterush](https://github.com/naterush)! I confirm that `pip install mitosheet` works.
