### ISSUE TITLE
spelling mistake during mitoinstaller install

### ISSUE THREAD

**Issue by williamdai8** [mito-ds/monorepo#358]
**Describe the bug**
Small issue, very minor, found a spelling mistake when running mitoinstaller install, 

Starting install...
Create mito user
Upgrade mitoinstaller
Setting up **enviornment** <--- **environment**
Check dependencies
Remove mitosheet3 if present
Install mitosheet
This might take a few moments...

**To Reproduce**
1. run python -m mitoinstaller install

Please include the relevant dataset if the bug you encountered is dataset specific. Make sure to anonymize the data properly.

**Expected behavior**
should be corrected to "environment"

**Screenshots**
![image](https://user-images.githubusercontent.com/38390775/172996852-a2c91d4a-2abb-4cf1-80c1-43045adea630.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by naterush** [comment]
Thanks for calling this out! Will get this fixed up asap. You know, I somehow always manage to misspell this one... smh.
