### ISSUE TITLE
Could support CONCATENATE function

### ISSUE THREAD

**Issue by zhugw** [mito-ds/monorepo#395]
Could you support `CONCATENATE ` function ? It's very useful.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/4953871/178868645-a6d4fa21-eb21-434f-87d1-58f3ae67fd9a.png">

**Comment by naterush** [comment]
@zhugw the `CONCAT` function does exactly what you're looking for. You can also see a full formula reference here: https://docs.trymito.io/how-to/interacting-with-your-data/mito-spreadsheet-formulas. 

Let me know if you have any more questions :)
