### ISSUE TITLE
ARM64 MacOs 11.6.1 import mitosheet module error

### ISSUE THREAD

**Issue by TheHerq** [mito-ds/monorepo#456]
**Bug description**

ModuleNotFoundError: No module named 'mitosheet'
<img width="1075" alt="mito_import_module_error" src="https://user-images.githubusercontent.com/81594979/188286740-7037c95d-7468-458f-b92f-79914a593644.png">

ARM64 MacOs 11.6.1
conda 4.13.0
python 3.9.13

I also checked on python 3.10.6 and same conda env (4.13.0) and on venv (python 3.10.6), always the same error. It looks like the jupyter notebook has not seen the mito sheet module installed, but of course the mitosheet module is installed in this environment..

However, everything works fine on an Intel processor:
Intel MacOs 11.5.2 (different MacOs ver, maybe that's the reason, though I do not suspect)
conda 4.13.0
python 3.9.13

I noticed that 'pip freeze' shows different packages on different machines:

[arm64_mito_3_9_13.txt](https://github.com/mito-ds/monorepo/files/9483337/arm64_mito_3_9_13.txt)

[intel_mito_3_9_13.txt](https://github.com/mito-ds/monorepo/files/9483338/intel_mito_3_9_13.txt)

**Reproduction**

1.  `conda create -n mito_test_1 python=3.9 notebook`
2. `conda activate mito_test_1`
3. `python -m pip install mitoinstaller`
4. `python -m mitoinstaller install`
5. `conda install -c conda-forge ipywidgets`

**Expected behavior**
Graphical interface of Mito in a jupyter notebook.

**Desktop:**
 - OS: MacMini arm64 MacOs 11.6.1
 - Browser [Chrome]
 - Mito Version [mitosheet==0.1.443] 

<img width="968" alt="mito_shell_scrs" src="https://user-images.githubusercontent.com/81594979/188287308-807fce32-0376-4806-a235-630e9a398332.png">

**Comment by naterush** [comment]
@TheHerq thanks for the bug report! We're digging into these Python version issues ASAP!

**Comment by naterush** [comment]
@TheHerq we're fixing this up in this PR: #455 

Will you be available to test this early tomorrow on your system?

**Comment by TheHerq** [comment]
@naterush sorry, I will be able to test on ARM only tomorrow evening (GMT + 2) because I will be using Intel (mobile one) during the day.

**Comment by naterush** [comment]
@TheHerq ok -- feel free to test now. I am on a ARM Mac and things are working well for Python 3.7-3.10. Let me know if you run into any further issues!

**Comment by TheHerq** [comment]
I did a quick test on ARM and the same error persists. Python 3.10.6 - venv. In the evening, I'll check if jupyter notebook works properly with other modules in this environment.

**Comment by TheHerq** [comment]
Problem solved. 
The problem was on my side, not Mito.
The error occurred because the Jupyter Notebook interpreter was looking at the wrong path with the modules installed.

**Comment by naterush** [comment]
Sweet!
