### ISSUE TITLE
Requirements are capping ipywidgets at 7.0.5

### ISSUE THREAD

**Issue by dcnadler** [mito-ds/monorepo#461]
setup.py is currently capping ipywidgets at 7.0.5

https://github.com/mito-ds/monorepo/blob/dev/mitosheet/setup.py#L103 should be:

```
'ipywidgets~=7.0',
```
or 
```
'ipywidgets==7.*',
```

I'm assuming it was ipywdigets>=8.0 that was breaking?

Thanks!

_Originally posted by @dcnadler in https://github.com/mito-ds/monorepo/issues/447#issuecomment-1232260218_

**Comment by aarondr77** [comment]
@dcnadler thanks for posting. We're fixing this up currently https://github.com/mito-ds/monorepo/pull/462

**Comment by dcnadler** [comment]
Great! Thanks @aarondr77!!

**Comment by naterush** [comment]
Fix is deployed, bumping the person. @dcnadler let me know if you have any further issues!

**Comment by dcnadler** [comment]
Turns out it was fixed in this commit: https://github.com/mito-ds/monorepo/commit/8e8e7cf4f901848f1e9ff0dbe0923f6cd83ea0b2

I just hadn't upgraded my package. Thanks for your help!!
