### ISSUE TITLE
combine_right pivot 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#521]
If we're applying pivot edits to the same pivot table in a row across different steps, we should combine them in the generated code.

Steps to reproduce
1. Create a pivot table
2. Close the pivot taskpane
3. Open the pivot taskpane
4. Edit the configuration
5. Notice that there are two pivot table generating code chunks in the generated code. 

We should overwrite the first one since there were no edits in between.

**Comment by naterush** [comment]
This has been fixed!
