### ISSUE TITLE
Formatting is limited in Formula Columns 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#54]
**Describe the bug**
The potential format options for a number series is dependent on whether the column is a `float` or an `int`. For most of the format options this isn't an issue. For example, the `Accounting` format option treats both floats and ints in the same manner. However, for the `default` and `plain text` formatting options, floats and ints are treated differently. Specifically, in the `plain text` and `default` formatting option, a `float` has a trailing `.0` and an `int` does not. 

In a data column, its easy to convert the dtype from `float` to `int` in order to get rid of the trailing `.0`. But there is no way to convert a formula column from a `float` to an `int`. The only dtype manipulation available is to use the `value` formula which converts a series to a number series. 

**To Reproduce**
1. Create a dataframe in Mito that has a column, `Date`, that is a datetime series. 
2. Create a new column, `Year`, and use the formula `=YEAR(Date)`
3. Notice that the values in the year column are formatted as `2,022.0`
4. Convert the format of the `Year` column from `Default` to `Plain Text` in order to get rid of the `,`
5. Notice that there is still a trailing `.0` and no way to remove it. 

**Expected behavior**
I expect to be able to remove the `.0` from my data. Preferably, I want to change the `dtype` of the column through the column control panel, even for formula columns. In lieu of that, I want to be able to use formulas to specify the dtype of my column with more granularity. For example, I expect there to be `INT` and `FLOAT` Mito formulas. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monteray
 - Browser: Firefox
 - Mito Version: 0.3.165

**Comment by naterush** [comment]
Interesting problem. It seems like there's a couple ways we could approach solving this. The simplest would be just adding a formatting option for showing 0 decimals (which is fine and totally easy, methinks). But this doesn't allow you to remove commas...

Other ways we could approach this:
1. Custom formats (python code? javascript code? idk). 
2. Splitting `number` Mito type -> `int` and `float` fully, and not treating them as the same type at all.

I might do a little investigation on (2). I'd be interested to see the implications.

**Comment by aarondr77** [comment]
A third approach, which is future proof for the world where we add more formatting options, is breaking out our existing formatting options into more sensible groups instead of lumping them all as one. 

For example, we could have `decimal place` and `number type` or something like that. Then, it would be easy to select `plain text` to say that the type of this data is just plain text that we don't want to stylize with commas, percentages, etc. And then we could also say `0 decimal places`. 

Being able to choose the type of the number and additional formatting options seems super sensible. If we added color formatting options, we would clearly want that broken out into a separate section as well.

**Comment by twelsh37** [comment]
> 2. Splitting `number` Mito type -> `int` and `float` fully, and not treating them as the same type at all.

I hope you don't mind me jumping in here.
I believe Option two from a users perspective is better. It will also allow you to address another bugbear. You can have a different icon to differentiate between int and floats. After all, ints and floats are different

**Comment by naterush** [comment]
@twelsh37 peep the above PR if you so desire! We've got new icons and sheet functions for treating FLOATs and INTs separate. By-by to treating things as just "numbers" - woo!
