### ISSUE TITLE
Cannot print from the API

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#576]
Developer experience bug where I can no longer print messages from the API, even if I turn Threaded to False, making it very hard to test & debug the api.

- Turn Threaded = False
- Add a print statement to the `get_code_snippets.py` file
- Restart your kernel, and refresh the browser
- Create a mitosheet and open the code snippets taskpane

**Comment by naterush** [comment]
1. Open the log console (View > Show Log Console), 
2. Then at the top of the Log Console, set Log Level to Debug
3. You should now see all prints as you normally do

This is a change in recent versions of Jupyter, or some dependency, I think!
