### ISSUE TITLE
`mitoinstaller install` should not launch jupyter noteboo

### ISSUE THREAD

**Issue by jpcbertoldo** [mito-ds/monorepo#578]
**Is your feature request related to a problem? Please describe.**

The automatic opening of jupyter notebook in the end of 

```bash
python -m mitoinstaller install --pro
```

makes it break higher level scripts (e.g. I use one to set up my environment).

**Describe the solution you'd like**

There should be an option to avoid this auto-launch.

**Comment by aarondr77** [comment]
Hey @jpcbertoldo thanks for posting! Working on a PR https://github.com/mito-ds/monorepo/pull/579 that will give you the option to turn off the automatic launch of Jupyter. 

If you don't mind sharing, I'd love to hear more about the script that you're using to set up your environment. This is the first I've heard that the auto launch of Jupyter causes issues.

**Comment by jpcbertoldo** [comment]
Thanks!

Sure. It's not a big deal of a script, just something i use to organize my setup. I have one conda env for jupyter lab and multiple others with the kernels, each with their dependencies, which I keep in conda env `.yml` files. 

Removing all the whistles and blows, it's basically this:

```bash
# `conda_env_exists` is defined in the script but was omitted

if ! conda_env_exists ${CONDA_ENV_NAME}; then
    conda env create --file ${ENV_YML_FPATH}
else 
    conda env update --name ${CONDA_ENV_NAME} --file ${ENV_YML_FPATH} --prune 
fi

conda activate ${CONDA_ENV_NAME}

python -m mitoinstaller install --pro

python -m ipykernel install --user --name=${ENVNAME}

```

So, it didn't really break actually, but it stops the normal flow of the script, which blocks me from using the script to automate these things.

**Comment by jpcbertoldo** [comment]
addressed by https://github.com/mito-ds/monorepo/pull/579
