### ISSUE TITLE
Multi Column Merge

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#70]
**Is your feature request related to a problem? Please describe.**
Select multiple columns from each sheet to use as the merge key.

**Describe the solution you'd like**
In the merge taskpane, the user should be required to select at least one column to use as the merge key for each sheet. However, they should have the ability to select multiple columns as well. 

Although the backend changes are really simple, this requires a design spec. The biggest complexity in the design is how to match columns for comparison in an intuitive way. 

Initial thinking would be to change the order of the taskpane so that there are two sections. In the first section, maybe laid out as two columns, the user selects the sheets to merge and the merge keys. Using columns could be a great way of making it obvious which columns are going to be compared. In the second section, the user selects which columns to keep from each sheet. 

**Describe alternatives you've considered**
The alternative is using the `concat` function to combine multiple columns into one and then merging. 

**Additional context**
This is one of the most commonly requested feature updates.

**Comment by naterush** [comment]
IMO, this issue needs a visual specification of what the feature looks like before it's ready for implementation. I'm gonna add a tag called `waiting on mockups` for this occasion. Let me know if you have thoughts. 

For my own sensibilities, I'll probably go for things that aren't waiting on mockups almost always when I'm in the mood to knock off some issues!

**Comment by aarondr77** [comment]
Yeah, definitely needs mockups

**Comment by naterush** [comment]
@aarondr77 while doing mockups for this, the other things I'd like to include:
1. Space for the error message when you have incompatible key types (and a specification of how we handle incompatible keys in the case of multiple keys -- what does this even mean?)
2. Space for adding multiple sheets? Maybe we can leave this out, but it does seem relevant if we're remaking mockups anyways... maybe leave out though.

**Comment by aarondr77** [comment]
Another thing we want to include in a full merge makeover is the ability to concat sheets vertically. This is continuing to be a common piece of feedback and with our new retention metrics, I think it becomes a bigger priority because its a blocker to using Mito. In fact, when we previously talked about this feature, we considered adding it to the import taskpane instead of the merge taskpane.

**Comment by naterush** [comment]
Note that this would also require updating the steps.
