### ISSUE TITLE
CI doesn't catch bug with setting cell value

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#76]
**Describe the bug**
The test `test_set_cell_value_convert_datetime` should be failing on dev, but all tests on dev are passing. 

If you go to the CI report for dev (commit: 4b533c4005226230c0073175cebf78af38268de3), you will see that most of the set_cell_value tests are being skipped. 

<img width="656" alt="Screen Shot 2022-02-16 at 2 48 54 PM" src="https://user-images.githubusercontent.com/18709905/154344276-3dddc887-e2ce-40e6-b4c5-8ae4ee8840b8.png">

In particular, this test is skipped because `sys.version_info.minor <= 6, reason="requires 3.7 or greater"`. 

This caused us to merge broken code into dev. Specifically, the code in dev does not support `datetime` or `timedelta` handling. 
<img width="1035" alt="Screen Shot 2022-02-16 at 2 52 00 PM" src="https://user-images.githubusercontent.com/18709905/154344718-3ead99f5-266c-46a4-9a05-87422425d576.png">

Questions:
- Does the CI in dev use a different version of pandas than CI in the PRs?

**Comment by naterush** [comment]
@aarondr77 to answer your question - yes! Note that this PR #67 _mainly goes about adding different versions of pandas to our CI_. 

As such, on dev, the old version of our CI is running, that just tests on the most recent version of pandas. The PR tests on all the new versions (check out the changes to the workflow .yml file in that PR that do this). 

Make sense?

**Comment by aarondr77** [comment]
That part makes sense, but according the .yml file on dev right now, that test should have ran because we were testing on 3.6, 3.7, and 3.8. To run that test, it just requires >= 3.7. So shouldn't our CI have caught this bug?

<img width="281" alt="Screen Shot 2022-02-16 at 3 03 51 PM" src="https://user-images.githubusercontent.com/18709905/154346689-0f5c1ebc-74ea-4098-aae3-375dc904abd2.png">

**Comment by naterush** [comment]
It's not just the Python version that matters here, but also the Pandas version. Check the CI on the PR and you can see that we do in fact vary both the _python_ and _pandas_ versions at the same time. That's why those bugs are popping up only on the PR (it's a specific pandas and python version that gets us here).

Closing, but please let me know if you have any questions about how this works!
