### ISSUE TITLE
Telemetery still gets sent when mitosheet.sheet() is NOT loaded

### ISSUE THREAD

**Issue by twelsh37** [mito-ds/monorepo#78]
**Describe the bug**
When running mito auto-generated code outside of Jupyter lab the telemetry (I think) upload fails and a corresponding error message is displayed

**To Reproduce**
Steps to reproduce the behaviour:
1. In Jupyter Notebook 
```
import mitosheet as mito
```

2. Read in some data. I used a local excel file
```
import pandas as pd
sheet_df_dictonary = pd.read_excel('risks.xlsx', sheet_name=['Sheet1'], skiprows=0)
Sheet1 = sheet_df_dictonary['Sheet1']
```

3. Do some column work
```
# Added column new-column-rmkw to df
df.insert(4, 'new-column-rmkw', 0)

# Renamed new-column-rmkw to Risk and Control ID in df
df.rename(columns={'new-column-rmkw': 'Risk and Control ID'}, inplace=True)
```

4. Execute 'df' in a new cell then wait about 5 minutes or whatever polling freq you have set and you will receive the following error which will be displayed beneath the dataframe.
`error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`
[risks.xlsx](https://github.com/mito-ds/monorepo/files/8088493/risks.xlsx)

I do not think this is dataset dependant.

Here is my full code
```
import mitosheet as mito

# Imported risks.xlsx
import pandas as pd
sheet_df_dictonary = pd.read_excel('risks.xlsx', sheet_name=['Sheet1'], skiprows=0)
Sheet1 = sheet_df_dictonary['Sheet1']

# Renamed Sheet1 to df
df = Sheet1

# Added column new-column-rmkw to df
df.insert(4, 'new-column-rmkw', 0)

# Renamed new-column-rmkw to Risk and Control ID in df
df.rename(columns={'new-column-rmkw': 'Risk and Control ID'}, inplace=True)

# Set new-column-rmkw in df to =CONCAT(Process ID, '-', Risk ID, '-', control ID, '-', Random)
df['Risk and Control ID'] = mito.CONCAT(df['Process ID'], '-', df['Risk ID'], '-', df['control ID'], '-', df['Random'])
```

**Expected behaviour**
I don't expect to see this error if I am using Mitosheet generated code outside of Jupyter lab.
Maybe something like the following pseudocode would take care of it

```
if mitosheet.sheet() exists:
    gather telemetry
else:
    don't gather telemetry
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4956770/154478524-31fb3de2-7807-445f-9e71-f773a3cdfebe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, Version 21H1, Build: 19043.1526 
 - Browser Chrome Version 98.0.4758.82 (Official Build) (64-bit)
 - Mito Version 0.3.157

**Additional context**

**Comment by naterush** [comment]
@twelsh37 thanks for posting this! To give a bit of context on this behavior, we currently collect telemetry for basic interactions with the `mitosheet` package generally - one of these actions is importing. In our telemetry here, as everywhere, we aim to take no personal/private data at all - so your data all remains on your machine. 

That being said, I think we can communicate this way better, and I appreciate you bringing it up! I'll add to our sprint next week that we're gonna a) improve our [FAQ](https://www.trymito.io/plans#private-telemetry-faq) to be more clear about what cases we handle, and b) improve our language in our signup flow. 

As always, you can turn _all_ telemetry by signup up for [Mito Pro](https://www.trymito.io/plans). Please let me know if you have any questions/comments/further thoughts about the above. I (and we all) think being clear and working w/ the community on how to best handle improving the tool while also giving users something they can trust is really important!
