### ISSUE TITLE
When you create and then rename a column the original column name persists in the auto-generated comment

### ISSUE THREAD

**Issue by twelsh37** [mito-ds/monorepo#79]
**Describe the bug**
When you Add a new column in Mitosheet.sheet() it is given a random name.
When you change that random name to something more meaning full the column header updates but the autogenerated comment does not use the NEW column name but use the ORIGINAL column name.

**To Reproduce**
1. Add a column
2. Rename the column
3. Note the comment above the rename statement. It knows what the old (Circled in black in screen shot)and new names (Circled in red in the screen shot) are.
4. Carry out another task in the renamed column. Note that it is still referencing the old column name.

This is not dataset specific.

**Expected behavior**
I would like the new column name to be persisted in the comments from the column rename  forward.

**Screenshots**
![image](https://user-images.githubusercontent.com/4956770/154495161-d21f6803-5345-46b5-ade4-bbbd2bd27bf3.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro, Version 21H1, Build: 19043.1526
- Browser Chrome Version 98.0.4758.82 (Official Build) (64-bit)
- Mito Version 0.3.157

**Comment by twelsh37** [comment]
@naterush Thanks for explaining the steps and describe function. 
On the comments. I don't really pay that much attention to them, but as this was such short code, and I was writing it up, this anomaly on the naming stuck out like a sore thumb. 
I do like the comments as it makes it easier to understand the code. I comment a lot when I am doing stuff. sometimes too much.
I definitely wouldn't suggest turning off comments if we don't like them we can always delete them when we take code elsewhere.

**Comment by naterush** [comment]
With the introduction of code chunks, we now get updated values for these! Nice!
