### ISSUE TITLE
Graph resizing broken in fullscreen mode

### ISSUE THREAD

**Issue by naterush** [mito-ds/monorepo#823]
1. Create a graph 
2. Go into full screen mode, notice that the graph does not change sizes
3. Edit the graph, notice that the graph still does not change size

<img width="1728" alt="Screenshot 2023-07-09 at 8 29 46 PM" src="https://github.com/mito-ds/monorepo/assets/18709905/84481ac8-37bc-4ab9-90a0-54d9b4a0d6dd">

**EDIT: on both Chrome and FF, it changes sizes for me. Will ping you to provide more details.**

_Originally posted by @aarondr77 in https://github.com/mito-ds/monorepo/issues/818#issuecomment-1627882838_

**Comment by aarondr77** [comment]
Update, resizing works properly on Chrome if there is only one mitsoheet in the notebook. However, if there are two it does not properly resize. 

https://github.com/mito-ds/monorepo/assets/18709905/ba847988-dfb6-4331-812a-87f8f66985dd

**Comment by naterush** [comment]
This was an issue fixed in this commit: https://github.com/mito-ds/monorepo/pull/818/commits/faa0e85ad8ad2422c81ba0374092a9b0f5fa6bb4

Avoid using document.getElementByID everywhere -- it doesn't work with multiple mitosheets. This is another reason a ShadowDom would be nice... btw.
