### ISSUE TITLE
Log dataframe name defaulting to df1, df2 ... 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#88]
**Describe the bug**
Occasionally, Mito doesn't read in dataframe names of passed arguments correctly. It defaults the dataframe names to being `df1`, `df2`, etc. This breaks all of the generated code because the dataframes that it references are non existent. 

I believe that its just a timing issue with the active code cell. 

**To Reproduce**
I'm unable to reproduce this bug. 

**Expected behavior**
Use the correct dataframe names, please!

**Additional context**
When this occurs, it usually goes away if you just rerun the mitosheet.sheet() call.

**Comment by naterush** [comment]
I think we should try to log this as a first step!
